#!/usr/bin/env python

import curses
import sys

screen = curses.initscr()

curses.noecho()
curses.curs_set()
screen.keypad(1)
screen.addstr("Permitted keys: Left/Right Arrow Keys, Up (yes), Down (no), ESC, ENTER and ??? for ON/OFF.\n"
              "                R for Refresh screen\n\n\n")

while True:
    try:
        event = screen.getch()
    except KeyboardInterrupt:
        curses.endwin()
        sys.exit(0)
    if event == curses.KEY_LEFT:
        screen.addstr("Left Arrow Key pressed\n")
    elif event == curses.KEY_RIGHT:
        screen.addstr("Right Arrow Key pressed\n")
    elif event == curses.KEY_UP:
        screen.addstr("UP Arrow Key pressed\n")
    elif event == curses.KEY_DOWN:
        screen.addstr("DOWN Arrow Key pressed\n")
    elif event == ord('r'):
        screen.addstr("r pressed\n")
    elif event == 10:  # ENTER
        screen.addstr("ENTER pressed\n")
    elif event == 27:  # ESCape
        screen.addstr("ESC pressed\n")
